### ISSUE TITLE
Empty sample after gating leads to error

### ISSUE THREAD

**Issue by max-brambach** [ym3141/EasyFlowQ#3]
When setting a gate such that it excludes all cells, EasyFlowQ raises an 'Unexpected Exception'.
Sample does not show up in Stats Window and is not plotted.

Expected behavior: No error message and an empty plot + inclusion in Stats window with e.g. cell number 0, % of total 0, ...

![image](https://github.com/ym3141/EasyFlowQ/assets/30292625/473defda-10ba-425e-9358-76fa262cfc12)

**Comment by ym3141** [comment]
Seems to be a bug for histogram only. The codes does not know how to deal with empty histograms.
