### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by IdRose** [ym3141/EasyFlowQ#7]
following happens whenever .fcs file is opened. there was no issue with Kaluza (proprietay software).
![Screenshot 2024-12-05 091557](https://github.com/user-attachments/assets/3b2b23d5-0099-4096-9f60-9622b32731ab)
![Screenshot 2024-12-05 091531](https://github.com/user-attachments/assets/b1760f26-5541-4865-8e0e-693306f91862)

**Comment by ym3141** [comment]
This is related how FlowCal handles flow machine's metadata (amplification_gain), and likely to be machine specific. I added a arbitrary protection on that in 7fc37b71b2ea8c0ad89cd76985ec03d1270cbd2f. 
It would be better if @IdRose attache a fcs file for further test.

**Comment by IdRose** [comment]
Github does no suppor fcs files, I'm attaching a link.
https://drive.google.com/file/d/1cqchm-ciO_8qfT9t9g6ape_k-wRtw6sn/view?usp=drive_link 
Also, I am not sure where to change the code, because the version downloaded through EasyFlowQ_WIN_Bundle.zip
does not have a file named [transform.py]
Much obliged.

**Comment by ym3141** [comment]
Should be fixed at this point (works on my computer). Please re-download from the latest release. 
Just technical note, it seems your machine set the gain for the "time" channel to be 0, causing this error.

**Comment by IdRose** [comment]
problem solved.
thanks!
